server:
    port: 8762
spring:
    application:
        name: eureka-ha-service
    profiles: peer2
eureka:
    instance:
        hostname: peer2
    client:
        serviceUrl:
            defaultZone: http://peer1:8761/eureka/

