server:
    port: 8763
#port: 8762
spring:
    application:
        name: eureka-provider
eureka:
    client:
        serviceUrl:
            defaultZone: http://Kevin:Kevin2018@localhost:8761/eureka/